# Generated by Django 5.2.17 on 2026-08-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('environment', 'Environment'), ('education', 'Education'), ('community', 'Community'), ('charity', 'Charity'), ('food', 'Food Support'), ('other', 'Other')], default='community', max_length=20),
        ),
    ]
